djangovue_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('game.urls'))
]

game/urls.py
from django.urls import path

from game.views import HomeView,MathGameView,AnagramGameView, GameScoreView,record_score


app_name="game"
urlpatterns = [
    path('',HomeView.as_view(),name='homepage'),
    path('math-game/',MathGameView.as_view(),name='math-game'),
    path('anagram-game/',AnagramGameView.as_view(),name='anagram-game'),
    path('record-score/',record_score,name='record-score'),
    path('game-scores/',GameScoreView.as_view(),name='game-scores'),
]

game/models.py
from django.db import models

class GameScore(models.Model) :
    MATH = 'MATH'
    ANAGRAM = 'ANAGRAM'
    
    GAME_CHOICES = [
        (MATH, 'Math'),
        (ANAGRAM, 'Anagram'),
    ]
    user_name = models.TextField()
    game  = models.TextField(choices=GAME_CHOICES,default=MATH)
    score = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

game/views.py
from django.views.generic import TemplateView
import json
from django.http import JsonResponse
from game.models import GameScore

class HomeView(TemplateView):
    template_name = "home.html"
class MathGameView(TemplateView):
    template_name = "math-game.html"
class AnagramGameView(TemplateView):
    template_name = "anagram-game.html"
    # def dispatch(self, request, *args, **kwargs):
    #     print("AnagramGameView is loading")
    #     return super().dispatch(request, *args, **kwargs)
class GameScoreView(TemplateView):
    template_name = "games-score.html"
    def get_context_data(self, **kwargs):
        context = super(GameScoreView, self).get_context_data(**kwargs)
        context['anagram_scores'] = GameScore.objects.filter(game__exact='ANAGRAM').order_by('-score')
        context['math_scores'] = GameScore.objects.filter(game__exact='MATH').order_by('-score')
        return context

def record_score(request):
    data = json.loads(request.body)
    user_name = data.get('user_name')
    game = data.get('game')
    score = data.get('score')

    new_score = GameScore.objects.create(
                user_name=user_name,
                game=game,
                score=score
            )
    new_score.save()
    
    response = {
        "success":True
    }

    return JsonResponse(response)

templates/anagram-game.html
{% extends 'base_vue.html' %}

{% block title %}
  Anagram
{% endblock %}
{% block main %}
  <h1>Anagram</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% block html %}
  <html lang="en">
    <head>
      {% block head %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>
          {% block title %}
          {% endblock %}| Games
        </title>
      {% endblock %}
    </head>
    <body>
      {% block body %}
        <header>
          <nav>
            <a href="{% url 'game:homepage' %}">Home</a> |
            <a href="{% url 'game:math-game' %}">Math</a> |
            <a href="{% url 'game:anagram-game' %}">Anagram</a> |
            <a href="{% url 'game:game-scores' %}">Game Score</a>
          </nav>
        </header>
        {% block main %}
        {% endblock %}
      {% endblock %}
    </body>
  </html>
{% endblock %}

templates/base_vue.html
{% extends 'base.html'%}
{%  block html  %}
<html lang="en">
  <head>
    {% block head %}{{ block.super }}{% endblock head %}
  <script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
  <body>
    {%block body%}
    {{ block.super }}
    <div id="app"></div>
    {% endblock body %}
  </body>
</html>
{% endblock html %}

templates/games-score.html
{% extends 'base.html' %}

{% block title %}
  Game Scores
{% endblock %}

{% block main %}
  <h1>Game Scores</h1>
  <h2>Math Game</h2>
  <ol>
    {% for score in math_scores %}
      <li>{{ score.score }}:({{ score.user_name }}-{{ score.created }})</li>
    {% endfor %}
  </ol>
  <h2>Anagram Game</h2>
  <ol>
    {% for score in anagram_scores %}
      <li>{{ score.score }}:({{ score.user_name }}-{{ score.created }})</li>
    {% endfor %}
  </ol>
{% endblock %}

templates/home.html
{% extends 'base_vue.html' %}

{% block title %}
  Home
{% endblock %}
{% block main %}
  <h1>Home</h1>
{% endblock %}

templates/math-game.html
{% extends 'base_vue.html' %}

{% block title %}
  Math
{% endblock %}
{% block main %}
  <h1>Math</h1>
{% endblock %}